add

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -1,15 +1,39 @@
-name: Changelog check
+name: Check CHANGELOG Version
 
 on:
-  pull_request:
-    branches: [ master, main, dev ]
+  push:
+    branches: [ main ]
 
 jobs:
-  changelog-check:
-    name: Check if CHANGELOG.md has been changed
+  check-changelog-version:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      # checks if the file CHANGELOG.md has had any changes on the current PR and has the correct format
-      - name: Check CHANGELOG.md
-        uses: dangoslen/changelog-enforcer@v3.0.0
+      - uses: actions/checkout@v4
+
+      - name: Extract version number from CHANGELOG.md
+        id: changelog-version
+        run: |
+          if [ -f CHANGELOG.md ]; then
+            VERSION=$(grep -Po '(?<=## \[Unreleased\]\n\n## \[)\d+\.\d+\.\d+' CHANGELOG.md | head -1)
+            if [ -z "$VERSION" ]; then
+              echo "Version number not found after ## [Unreleased]"
+              exit 1
+            else
+              echo "Found version: $VERSION"
+              echo "::set-output name=version::$VERSION"
+            fi
+          else
+            echo "CHANGELOG.md file does not exist"
+            exit 1
+          fi
+
+      - name: Check if version matches expected format
+        run: |
+          VERSION=${{ steps.changelog-version.outputs.version }}
+          # Example check: ensure version is not empty and follows a specific pattern
+          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Version format is incorrect or not found: $VERSION"
+            exit 1
+          else
+            echo "Version format is correct: $VERSION"
+          fi
